/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2014-05-14 15:01:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class showLayerDetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;
private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_1;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("utils:isVectorLayer", uk.ac.rdg.resc.ncwms.util.WmsUtils.class, "isVectorLayer", new Class[] {uk.ac.rdg.resc.ncwms.wms.Layer.class});
  _jspx_fnmap_1= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("utils:getTimeAxisUnits", uk.ac.rdg.resc.ncwms.util.WmsUtils.class, "getTimeAxisUnits", new Class[] {org.joda.time.Chronology.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/taglib/wms/wmsUtils.tld", Long.valueOf(1400086848000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/plain;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write(" ");
      out.write('\n');

response.setHeader("Cache-Control","no-cache"); //HTTP 1.1
response.setHeader("Pragma","no-cache"); //HTTP 1.0
response.setDateHeader ("Expires", 0); //prevents caching at the proxy server

      out.write('\n');
      out.write('\n');
      if (_jspx_meth_json_005fobject_005f0(_jspx_page_context))
        return;
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_json_005fobject_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  json:object
    atg.taglib.json.JsonObjectTag _jspx_th_json_005fobject_005f0 = (new atg.taglib.json.JsonObjectTag());
    _jsp_instancemanager.newInstance(_jspx_th_json_005fobject_005f0);
    _jspx_th_json_005fobject_005f0.setJspContext(_jspx_page_context);
    _jspx_th_json_005fobject_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_json_005fobject_005f0, null));
    _jspx_th_json_005fobject_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_json_005fobject_005f0);
    return false;
  }

  private boolean _jspx_meth_json_005fproperty_005f0(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  json:property
    atg.taglib.json.JsonPropertyTag _jspx_th_json_005fproperty_005f0 = (new atg.taglib.json.JsonPropertyTag());
    _jsp_instancemanager.newInstance(_jspx_th_json_005fproperty_005f0);
    _jspx_th_json_005fproperty_005f0.setJspContext(_jspx_page_context);
    _jspx_th_json_005fproperty_005f0.setParent(_jspx_parent);
    // /WEB-INF/jsp/showLayerDetails.jsp(24,4) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_json_005fproperty_005f0.setName("units");
    // /WEB-INF/jsp/showLayerDetails.jsp(24,4) name = value type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_json_005fproperty_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${layer.units}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    _jspx_th_json_005fproperty_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_json_005fproperty_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
    // /WEB-INF/jsp/showLayerDetails.jsp(26,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("bbox");
    // /WEB-INF/jsp/showLayerDetails.jsp(26,4) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${layer.geographicBoundingBox}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      throw new javax.servlet.jsp.SkipPageException();
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_json_005farray_005f0(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  json:array
    atg.taglib.json.JsonArrayTag _jspx_th_json_005farray_005f0 = (new atg.taglib.json.JsonArrayTag());
    _jsp_instancemanager.newInstance(_jspx_th_json_005farray_005f0);
    _jspx_th_json_005farray_005f0.setJspContext(_jspx_page_context);
    _jspx_th_json_005farray_005f0.setParent(_jspx_parent);
    // /WEB-INF/jsp/showLayerDetails.jsp(27,4) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_json_005farray_005f0.setName("bbox");
    _jspx_th_json_005farray_005f0.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_json_005farray_005f0, null));
    _jspx_th_json_005farray_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_json_005farray_005f0);
    return false;
  }

  private boolean _jspx_meth_json_005fproperty_005f1(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  json:property
    atg.taglib.json.JsonPropertyTag _jspx_th_json_005fproperty_005f1 = (new atg.taglib.json.JsonPropertyTag());
    _jsp_instancemanager.newInstance(_jspx_th_json_005fproperty_005f1);
    _jspx_th_json_005fproperty_005f1.setJspContext(_jspx_page_context);
    _jspx_th_json_005fproperty_005f1.setParent(_jspx_parent);
    _jspx_th_json_005fproperty_005f1.setJspBody(new Helper( 2, _jspx_page_context, _jspx_th_json_005fproperty_005f1, null));
    _jspx_th_json_005fproperty_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_json_005fproperty_005f1);
    return false;
  }

  private boolean _jspx_meth_json_005fproperty_005f2(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  json:property
    atg.taglib.json.JsonPropertyTag _jspx_th_json_005fproperty_005f2 = (new atg.taglib.json.JsonPropertyTag());
    _jsp_instancemanager.newInstance(_jspx_th_json_005fproperty_005f2);
    _jspx_th_json_005fproperty_005f2.setJspContext(_jspx_page_context);
    _jspx_th_json_005fproperty_005f2.setParent(_jspx_parent);
    _jspx_th_json_005fproperty_005f2.setJspBody(new Helper( 3, _jspx_page_context, _jspx_th_json_005fproperty_005f2, null));
    _jspx_th_json_005fproperty_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_json_005fproperty_005f2);
    return false;
  }

  private boolean _jspx_meth_json_005fproperty_005f3(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  json:property
    atg.taglib.json.JsonPropertyTag _jspx_th_json_005fproperty_005f3 = (new atg.taglib.json.JsonPropertyTag());
    _jsp_instancemanager.newInstance(_jspx_th_json_005fproperty_005f3);
    _jspx_th_json_005fproperty_005f3.setJspContext(_jspx_page_context);
    _jspx_th_json_005fproperty_005f3.setParent(_jspx_parent);
    _jspx_th_json_005fproperty_005f3.setJspBody(new Helper( 4, _jspx_page_context, _jspx_th_json_005fproperty_005f3, null));
    _jspx_th_json_005fproperty_005f3.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_json_005fproperty_005f3);
    return false;
  }

  private boolean _jspx_meth_json_005fproperty_005f4(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  json:property
    atg.taglib.json.JsonPropertyTag _jspx_th_json_005fproperty_005f4 = (new atg.taglib.json.JsonPropertyTag());
    _jsp_instancemanager.newInstance(_jspx_th_json_005fproperty_005f4);
    _jspx_th_json_005fproperty_005f4.setJspContext(_jspx_page_context);
    _jspx_th_json_005fproperty_005f4.setParent(_jspx_parent);
    _jspx_th_json_005fproperty_005f4.setJspBody(new Helper( 5, _jspx_page_context, _jspx_th_json_005fproperty_005f4, null));
    _jspx_th_json_005fproperty_005f4.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_json_005fproperty_005f4);
    return false;
  }

  private boolean _jspx_meth_json_005farray_005f1(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  json:array
    atg.taglib.json.JsonArrayTag _jspx_th_json_005farray_005f1 = (new atg.taglib.json.JsonArrayTag());
    _jsp_instancemanager.newInstance(_jspx_th_json_005farray_005f1);
    _jspx_th_json_005farray_005f1.setJspContext(_jspx_page_context);
    _jspx_th_json_005farray_005f1.setParent(_jspx_parent);
    // /WEB-INF/jsp/showLayerDetails.jsp(34,4) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_json_005farray_005f1.setName("scaleRange");
    _jspx_th_json_005farray_005f1.setJspBody(new Helper( 6, _jspx_page_context, _jspx_th_json_005farray_005f1, null));
    _jspx_th_json_005farray_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_json_005farray_005f1);
    return false;
  }

  private boolean _jspx_meth_json_005fproperty_005f5(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  json:property
    atg.taglib.json.JsonPropertyTag _jspx_th_json_005fproperty_005f5 = (new atg.taglib.json.JsonPropertyTag());
    _jsp_instancemanager.newInstance(_jspx_th_json_005fproperty_005f5);
    _jspx_th_json_005fproperty_005f5.setJspContext(_jspx_page_context);
    _jspx_th_json_005fproperty_005f5.setParent(_jspx_parent);
    _jspx_th_json_005fproperty_005f5.setJspBody(new Helper( 7, _jspx_page_context, _jspx_th_json_005fproperty_005f5, null));
    _jspx_th_json_005fproperty_005f5.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_json_005fproperty_005f5);
    return false;
  }

  private boolean _jspx_meth_json_005fproperty_005f6(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  json:property
    atg.taglib.json.JsonPropertyTag _jspx_th_json_005fproperty_005f6 = (new atg.taglib.json.JsonPropertyTag());
    _jsp_instancemanager.newInstance(_jspx_th_json_005fproperty_005f6);
    _jspx_th_json_005fproperty_005f6.setJspContext(_jspx_page_context);
    _jspx_th_json_005fproperty_005f6.setParent(_jspx_parent);
    _jspx_th_json_005fproperty_005f6.setJspBody(new Helper( 8, _jspx_page_context, _jspx_th_json_005fproperty_005f6, null));
    _jspx_th_json_005fproperty_005f6.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_json_005fproperty_005f6);
    return false;
  }

  private boolean _jspx_meth_json_005fproperty_005f7(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  json:property
    atg.taglib.json.JsonPropertyTag _jspx_th_json_005fproperty_005f7 = (new atg.taglib.json.JsonPropertyTag());
    _jsp_instancemanager.newInstance(_jspx_th_json_005fproperty_005f7);
    _jspx_th_json_005fproperty_005f7.setJspContext(_jspx_page_context);
    _jspx_th_json_005fproperty_005f7.setParent(_jspx_parent);
    // /WEB-INF/jsp/showLayerDetails.jsp(39,4) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_json_005fproperty_005f7.setName("numColorBands");
    // /WEB-INF/jsp/showLayerDetails.jsp(39,4) name = value type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_json_005fproperty_005f7.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${layer.defaultNumColorBands}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    _jspx_th_json_005fproperty_005f7.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_json_005fproperty_005f7);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f1.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
    // /WEB-INF/jsp/showLayerDetails.jsp(41,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setVar("styles");
    // /WEB-INF/jsp/showLayerDetails.jsp(41,4) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setValue(new String("boxfill"));
    int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
    if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      throw new javax.servlet.jsp.SkipPageException();
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
    // /WEB-INF/jsp/showLayerDetails.jsp(42,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${utils:isVectorLayer(layer)}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("        ");
        if (_jspx_meth_c_005fset_005f2(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("    ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      throw new javax.servlet.jsp.SkipPageException();
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /WEB-INF/jsp/showLayerDetails.jsp(43,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f2.setVar("styles");
    // /WEB-INF/jsp/showLayerDetails.jsp(43,8) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f2.setValue(new String("vector,boxfill"));
    int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
    if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      throw new javax.servlet.jsp.SkipPageException();
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
    return false;
  }

  private boolean _jspx_meth_json_005farray_005f2(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  json:array
    atg.taglib.json.JsonArrayTag _jspx_th_json_005farray_005f2 = (new atg.taglib.json.JsonArrayTag());
    _jsp_instancemanager.newInstance(_jspx_th_json_005farray_005f2);
    _jspx_th_json_005farray_005f2.setJspContext(_jspx_page_context);
    _jspx_th_json_005farray_005f2.setParent(_jspx_parent);
    // /WEB-INF/jsp/showLayerDetails.jsp(45,4) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_json_005farray_005f2.setName("supportedStyles");
    // /WEB-INF/jsp/showLayerDetails.jsp(45,4) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_json_005farray_005f2.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${styles}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    _jspx_th_json_005farray_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_json_005farray_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
    // /WEB-INF/jsp/showLayerDetails.jsp(47,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty layer.elevationValues}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("        ");
        if (_jspx_meth_json_005fobject_005f1(_jspx_th_c_005fif_005f1, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("    ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      throw new javax.servlet.jsp.SkipPageException();
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_json_005fobject_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  json:object
    atg.taglib.json.JsonObjectTag _jspx_th_json_005fobject_005f1 = (new atg.taglib.json.JsonObjectTag());
    _jsp_instancemanager.newInstance(_jspx_th_json_005fobject_005f1);
    _jspx_th_json_005fobject_005f1.setJspContext(_jspx_page_context);
    _jspx_th_json_005fobject_005f1.setParent(_jspx_th_c_005fif_005f1);
    // /WEB-INF/jsp/showLayerDetails.jsp(48,8) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_json_005fobject_005f1.setName("zaxis");
    _jspx_th_json_005fobject_005f1.setJspBody(new Helper( 9, _jspx_page_context, _jspx_th_json_005fobject_005f1, null));
    _jspx_th_json_005fobject_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_json_005fobject_005f1);
    return false;
  }

  private boolean _jspx_meth_json_005fproperty_005f8(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  json:property
    atg.taglib.json.JsonPropertyTag _jspx_th_json_005fproperty_005f8 = (new atg.taglib.json.JsonPropertyTag());
    _jsp_instancemanager.newInstance(_jspx_th_json_005fproperty_005f8);
    _jspx_th_json_005fproperty_005f8.setJspContext(_jspx_page_context);
    _jspx_th_json_005fproperty_005f8.setParent(_jspx_parent);
    // /WEB-INF/jsp/showLayerDetails.jsp(49,12) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_json_005fproperty_005f8.setName("units");
    // /WEB-INF/jsp/showLayerDetails.jsp(49,12) name = value type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_json_005fproperty_005f8.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${layer.elevationUnits}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    _jspx_th_json_005fproperty_005f8.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_json_005fproperty_005f8);
    return false;
  }

  private boolean _jspx_meth_json_005fproperty_005f9(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  json:property
    atg.taglib.json.JsonPropertyTag _jspx_th_json_005fproperty_005f9 = (new atg.taglib.json.JsonPropertyTag());
    _jsp_instancemanager.newInstance(_jspx_th_json_005fproperty_005f9);
    _jspx_th_json_005fproperty_005f9.setJspContext(_jspx_page_context);
    _jspx_th_json_005fproperty_005f9.setParent(_jspx_parent);
    // /WEB-INF/jsp/showLayerDetails.jsp(50,12) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_json_005fproperty_005f9.setName("positive");
    // /WEB-INF/jsp/showLayerDetails.jsp(50,12) name = value type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_json_005fproperty_005f9.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${layer.elevationPositive}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    _jspx_th_json_005fproperty_005f9.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_json_005fproperty_005f9);
    return false;
  }

  private boolean _jspx_meth_json_005farray_005f3(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  json:array
    atg.taglib.json.JsonArrayTag _jspx_th_json_005farray_005f3 = (new atg.taglib.json.JsonArrayTag());
    _jsp_instancemanager.newInstance(_jspx_th_json_005farray_005f3);
    _jspx_th_json_005farray_005f3.setJspContext(_jspx_page_context);
    _jspx_th_json_005farray_005f3.setParent(_jspx_parent);
    // /WEB-INF/jsp/showLayerDetails.jsp(51,12) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_json_005farray_005f3.setName("values");
    // /WEB-INF/jsp/showLayerDetails.jsp(51,12) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_json_005farray_005f3.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${layer.elevationValues}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    _jspx_th_json_005farray_005f3.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_json_005farray_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
    // /WEB-INF/jsp/showLayerDetails.jsp(55,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty layer.timeValues}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("        ");
        if (_jspx_meth_json_005fobject_005f2(_jspx_th_c_005fif_005f2, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("        ");
        out.write("\n");
        out.write("        ");
        if (_jspx_meth_json_005fproperty_005f10(_jspx_th_c_005fif_005f2, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("        ");
        out.write("\n");
        out.write("        ");
        if (_jspx_meth_json_005fproperty_005f11(_jspx_th_c_005fif_005f2, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("    ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      throw new javax.servlet.jsp.SkipPageException();
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }

  private boolean _jspx_meth_json_005fobject_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  json:object
    atg.taglib.json.JsonObjectTag _jspx_th_json_005fobject_005f2 = (new atg.taglib.json.JsonObjectTag());
    _jsp_instancemanager.newInstance(_jspx_th_json_005fobject_005f2);
    _jspx_th_json_005fobject_005f2.setJspContext(_jspx_page_context);
    _jspx_th_json_005fobject_005f2.setParent(_jspx_th_c_005fif_005f2);
    // /WEB-INF/jsp/showLayerDetails.jsp(56,8) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_json_005fobject_005f2.setName("datesWithData");
    _jspx_th_json_005fobject_005f2.setJspBody(new Helper( 10, _jspx_page_context, _jspx_th_json_005fobject_005f2, null));
    _jspx_th_json_005fobject_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_json_005fobject_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
    // /WEB-INF/jsp/showLayerDetails.jsp(57,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("year");
    // /WEB-INF/jsp/showLayerDetails.jsp(57,12) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${datesWithData}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                ");
          if (_jspx_meth_json_005fobject_005f3(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        throw new javax.servlet.jsp.SkipPageException();
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_json_005fobject_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  json:object
    atg.taglib.json.JsonObjectTag _jspx_th_json_005fobject_005f3 = (new atg.taglib.json.JsonObjectTag());
    _jsp_instancemanager.newInstance(_jspx_th_json_005fobject_005f3);
    _jspx_th_json_005fobject_005f3.setJspContext(_jspx_page_context);
    _jspx_th_json_005fobject_005f3.setParent(_jspx_th_c_005fforEach_005f0);
    // /WEB-INF/jsp/showLayerDetails.jsp(58,16) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_json_005fobject_005f3.setName((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${year.key}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    _jspx_th_json_005fobject_005f3.setJspBody(new Helper( 11, _jspx_page_context, _jspx_th_json_005fobject_005f3, _jspx_push_body_count_c_005fforEach_005f0));
    _jspx_th_json_005fobject_005f3.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_json_005fobject_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
    // /WEB-INF/jsp/showLayerDetails.jsp(59,20) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("month");
    // /WEB-INF/jsp/showLayerDetails.jsp(59,20) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${year.value}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                        ");
          if (_jspx_meth_json_005farray_005f4(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        throw new javax.servlet.jsp.SkipPageException();
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_json_005farray_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  json:array
    atg.taglib.json.JsonArrayTag _jspx_th_json_005farray_005f4 = (new atg.taglib.json.JsonArrayTag());
    _jsp_instancemanager.newInstance(_jspx_th_json_005farray_005f4);
    _jspx_th_json_005farray_005f4.setJspContext(_jspx_page_context);
    _jspx_th_json_005farray_005f4.setParent(_jspx_th_c_005fforEach_005f1);
    // /WEB-INF/jsp/showLayerDetails.jsp(60,24) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_json_005farray_005f4.setName((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${month.key}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    // /WEB-INF/jsp/showLayerDetails.jsp(60,24) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_json_005farray_005f4.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${month.value}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    _jspx_th_json_005farray_005f4.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_json_005farray_005f4);
    return false;
  }

  private boolean _jspx_meth_json_005fproperty_005f10(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  json:property
    atg.taglib.json.JsonPropertyTag _jspx_th_json_005fproperty_005f10 = (new atg.taglib.json.JsonPropertyTag());
    _jsp_instancemanager.newInstance(_jspx_th_json_005fproperty_005f10);
    _jspx_th_json_005fproperty_005f10.setJspContext(_jspx_page_context);
    _jspx_th_json_005fproperty_005f10.setParent(_jspx_th_c_005fif_005f2);
    // /WEB-INF/jsp/showLayerDetails.jsp(67,8) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_json_005fproperty_005f10.setName("nearestTimeIso");
    // /WEB-INF/jsp/showLayerDetails.jsp(67,8) name = value type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_json_005fproperty_005f10.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nearestTimeIso}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    _jspx_th_json_005fproperty_005f10.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_json_005fproperty_005f10);
    return false;
  }

  private boolean _jspx_meth_json_005fproperty_005f11(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  json:property
    atg.taglib.json.JsonPropertyTag _jspx_th_json_005fproperty_005f11 = (new atg.taglib.json.JsonPropertyTag());
    _jsp_instancemanager.newInstance(_jspx_th_json_005fproperty_005f11);
    _jspx_th_json_005fproperty_005f11.setJspContext(_jspx_page_context);
    _jspx_th_json_005fproperty_005f11.setParent(_jspx_th_c_005fif_005f2);
    // /WEB-INF/jsp/showLayerDetails.jsp(70,8) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_json_005fproperty_005f11.setName("timeAxisUnits");
    // /WEB-INF/jsp/showLayerDetails.jsp(70,8) name = value type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_json_005fproperty_005f11.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${utils:getTimeAxisUnits(layer.chronology)}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_1, false));
    _jspx_th_json_005fproperty_005f11.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_json_005fproperty_005f11);
    return false;
  }

  private boolean _jspx_meth_json_005fproperty_005f12(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  json:property
    atg.taglib.json.JsonPropertyTag _jspx_th_json_005fproperty_005f12 = (new atg.taglib.json.JsonPropertyTag());
    _jsp_instancemanager.newInstance(_jspx_th_json_005fproperty_005f12);
    _jspx_th_json_005fproperty_005f12.setJspContext(_jspx_page_context);
    _jspx_th_json_005fproperty_005f12.setParent(_jspx_parent);
    // /WEB-INF/jsp/showLayerDetails.jsp(73,4) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_json_005fproperty_005f12.setName("moreInfo");
    // /WEB-INF/jsp/showLayerDetails.jsp(73,4) name = value type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_json_005fproperty_005f12.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${layer.dataset.moreInfoUrl}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    _jspx_th_json_005fproperty_005f12.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_json_005fproperty_005f12);
    return false;
  }

  private boolean _jspx_meth_json_005fproperty_005f13(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  json:property
    atg.taglib.json.JsonPropertyTag _jspx_th_json_005fproperty_005f13 = (new atg.taglib.json.JsonPropertyTag());
    _jsp_instancemanager.newInstance(_jspx_th_json_005fproperty_005f13);
    _jspx_th_json_005fproperty_005f13.setJspContext(_jspx_page_context);
    _jspx_th_json_005fproperty_005f13.setParent(_jspx_parent);
    // /WEB-INF/jsp/showLayerDetails.jsp(74,4) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_json_005fproperty_005f13.setName("copyright");
    // /WEB-INF/jsp/showLayerDetails.jsp(74,4) name = value type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_json_005fproperty_005f13.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${layer.dataset.copyrightStatement}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    _jspx_th_json_005fproperty_005f13.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_json_005fproperty_005f13);
    return false;
  }

  private boolean _jspx_meth_json_005farray_005f5(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  json:array
    atg.taglib.json.JsonArrayTag _jspx_th_json_005farray_005f5 = (new atg.taglib.json.JsonArrayTag());
    _jsp_instancemanager.newInstance(_jspx_th_json_005farray_005f5);
    _jspx_th_json_005farray_005f5.setJspContext(_jspx_page_context);
    _jspx_th_json_005farray_005f5.setParent(_jspx_parent);
    // /WEB-INF/jsp/showLayerDetails.jsp(75,4) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_json_005farray_005f5.setName("palettes");
    // /WEB-INF/jsp/showLayerDetails.jsp(75,4) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_json_005farray_005f5.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${paletteNames}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    _jspx_th_json_005farray_005f5.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_json_005farray_005f5);
    return false;
  }

  private boolean _jspx_meth_json_005fproperty_005f14(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  json:property
    atg.taglib.json.JsonPropertyTag _jspx_th_json_005fproperty_005f14 = (new atg.taglib.json.JsonPropertyTag());
    _jsp_instancemanager.newInstance(_jspx_th_json_005fproperty_005f14);
    _jspx_th_json_005fproperty_005f14.setJspContext(_jspx_page_context);
    _jspx_th_json_005fproperty_005f14.setParent(_jspx_parent);
    // /WEB-INF/jsp/showLayerDetails.jsp(76,4) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_json_005fproperty_005f14.setName("defaultPalette");
    // /WEB-INF/jsp/showLayerDetails.jsp(76,4) name = value type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_json_005fproperty_005f14.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${layer.defaultColorPalette.name}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    _jspx_th_json_005fproperty_005f14.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_json_005fproperty_005f14);
    return false;
  }

  private boolean _jspx_meth_json_005fproperty_005f15(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  json:property
    atg.taglib.json.JsonPropertyTag _jspx_th_json_005fproperty_005f15 = (new atg.taglib.json.JsonPropertyTag());
    _jsp_instancemanager.newInstance(_jspx_th_json_005fproperty_005f15);
    _jspx_th_json_005fproperty_005f15.setJspContext(_jspx_page_context);
    _jspx_th_json_005fproperty_005f15.setParent(_jspx_parent);
    // /WEB-INF/jsp/showLayerDetails.jsp(77,4) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_json_005fproperty_005f15.setName("logScaling");
    // /WEB-INF/jsp/showLayerDetails.jsp(77,4) name = value type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_json_005fproperty_005f15.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${layer.logScaling}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    _jspx_th_json_005fproperty_005f15.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_json_005fproperty_005f15);
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private javax.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, javax.servlet.jsp.JspContext jspContext, javax.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_json_005fproperty_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\n");
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_c_005fset_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_json_005farray_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\n");
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_json_005farray_005f1(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\n");
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_json_005fproperty_005f7(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\n");
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_c_005fset_005f1(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_json_005farray_005f2(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\n");
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f1(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\n");
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f2(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\n");
      out.write("    \n");
      out.write("    ");
      if (_jspx_meth_json_005fproperty_005f12(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_json_005fproperty_005f13(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_json_005farray_005f5(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_json_005fproperty_005f14(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_json_005fproperty_005f15(_jspx_parent, _jspx_page_context))
        return true;
      out.write('\n');
      return false;
    }
    public boolean invoke1( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\n");
      out.write("        ");
      if (_jspx_meth_json_005fproperty_005f1(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\n");
      out.write("        ");
      if (_jspx_meth_json_005fproperty_005f2(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\n");
      out.write("        ");
      if (_jspx_meth_json_005fproperty_005f3(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\n");
      out.write("        ");
      if (_jspx_meth_json_005fproperty_005f4(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\n");
      out.write("    ");
      return false;
    }
    public boolean invoke2( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bbox.westBoundLongitude}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      return false;
    }
    public boolean invoke3( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bbox.southBoundLatitude}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      return false;
    }
    public boolean invoke4( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bbox.eastBoundLongitude}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      return false;
    }
    public boolean invoke5( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bbox.northBoundLatitude}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      return false;
    }
    public boolean invoke6( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\n");
      out.write("        ");
      if (_jspx_meth_json_005fproperty_005f5(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\n");
      out.write("        ");
      if (_jspx_meth_json_005fproperty_005f6(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\n");
      out.write("    ");
      return false;
    }
    public boolean invoke7( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${layer.approxValueRange.minimum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      return false;
    }
    public boolean invoke8( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${layer.approxValueRange.maximum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      return false;
    }
    public boolean invoke9( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_json_005fproperty_005f8(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_json_005fproperty_005f9(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_json_005farray_005f3(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\n");
      out.write("        ");
      return false;
    }
    public boolean invoke10( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\n");
      out.write("        ");
      return false;
    }
    public boolean invoke11( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\n");
      out.write("                    ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_parent, _jspx_page_context, _jspx_push_body_count))
        return true;
      out.write("\n");
      out.write("                ");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws javax.servlet.jsp.JspException
    {
      javax.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(javax.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
          case 2:
            invoke2( out );
            break;
          case 3:
            invoke3( out );
            break;
          case 4:
            invoke4( out );
            break;
          case 5:
            invoke5( out );
            break;
          case 6:
            invoke6( out );
            break;
          case 7:
            invoke7( out );
            break;
          case 8:
            invoke8( out );
            break;
          case 9:
            invoke9( out );
            break;
          case 10:
            invoke10( out );
            break;
          case 11:
            invoke11( out );
            break;
        }
        jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof javax.servlet.jsp.SkipPageException)
            throw (javax.servlet.jsp.SkipPageException) e;
        throw new javax.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
